table FactEmployee
	lineageTag: 26942b2b-9fef-4a0c-b932-e6bb7d33e9ea

	column EmployeeNumber
		dataType: int64
		lineageTag: 225fa7ce-d7d0-4df3-8929-2b082f0f62ba
		summarizeBy: none
		sourceColumn: EmployeeNumber

	column DepartmentKey
		dataType: int64
		isHidden
		lineageTag: 58ea7256-8283-48db-887d-316ef2b66031
		summarizeBy: none
		sourceColumn: DepartmentKey

	column JobRoleKey
		dataType: int64
		isHidden
		lineageTag: 5626315f-b47a-4c59-b3bd-65715bc72e1c
		summarizeBy: none
		sourceColumn: JobRoleKey

	column EducationKey
		dataType: int64
		isHidden
		lineageTag: 18c23df5-9a8e-4e15-a87c-152215e1d05d
		summarizeBy: none
		sourceColumn: EducationKey

	column DemographicsKey
		dataType: int64
		isHidden
		lineageTag: 70ee1006-2e6a-442c-b0e5-04406e679001
		summarizeBy: none
		sourceColumn: DemographicsKey

	column TravelKey
		dataType: int64
		isHidden
		lineageTag: 50ae89f7-3e24-4296-84ca-5af542f6b474
		summarizeBy: none
		sourceColumn: TravelKey

	column Attrition
		dataType: string
		lineageTag: adebd247-5a8f-43bd-8d2f-9b0aa9eb5c1c
		summarizeBy: none
		sourceColumn: Attrition

	column OverTime
		dataType: string
		lineageTag: 593a35c7-cb03-450a-bcca-bade1ceebbce
		summarizeBy: none
		sourceColumn: OverTime

	column Age
		dataType: int64
		lineageTag: 6943751e-7d29-4cd3-8e04-78e2e84688e9
		summarizeBy: none
		sourceColumn: Age

	column MonthlyIncome
		dataType: int64
		lineageTag: 3830c3ff-24bc-4dcf-a109-76a74015d814
		summarizeBy: none
		sourceColumn: MonthlyIncome

	column MonthlyRate
		dataType: int64
		lineageTag: 6cd7b235-c7ef-497d-8304-acf4ecaa81a0
		summarizeBy: none
		sourceColumn: MonthlyRate

	column DailyRate
		dataType: int64
		lineageTag: 332380f9-2931-4438-b9ec-83a17e422b5f
		summarizeBy: none
		sourceColumn: DailyRate

	column HourlyRate
		dataType: int64
		lineageTag: b4b46dce-d237-430f-a0ae-452f3f8b55d6
		summarizeBy: none
		sourceColumn: HourlyRate

	column PercentSalaryHike
		dataType: int64
		lineageTag: 654c1d90-706a-4fbe-a6f8-067c96b67336
		summarizeBy: none
		sourceColumn: PercentSalaryHike

	column DistanceFromHome
		dataType: int64
		lineageTag: 2f3cfac8-d4a0-4ae8-ad91-8534ae2329b1
		summarizeBy: none
		sourceColumn: DistanceFromHome

	column TotalWorkingYears
		dataType: int64
		lineageTag: c0125c43-cd82-4afc-bc1e-86cacd6c99ef
		summarizeBy: none
		sourceColumn: TotalWorkingYears

	column YearsAtCompany
		dataType: int64
		lineageTag: 4370308e-d059-4968-abbe-1cfc9d47e3df
		summarizeBy: none
		sourceColumn: YearsAtCompany

	column YearsInCurrentRole
		dataType: int64
		lineageTag: 92ff1588-bfae-4787-9502-65ba771a89ad
		summarizeBy: none
		sourceColumn: YearsInCurrentRole

	column YearsSinceLastPromotion
		dataType: int64
		lineageTag: b7da13ac-6e73-4ae7-bed3-703d2095ad01
		summarizeBy: none
		sourceColumn: YearsSinceLastPromotion

	column YearsWithCurrManager
		dataType: int64
		lineageTag: d71c235d-f2a0-413e-b8a4-33e647047ade
		summarizeBy: none
		sourceColumn: YearsWithCurrManager

	column NumCompaniesWorked
		dataType: int64
		lineageTag: 239316e4-ef96-4ac1-9967-f3a02f268b80
		summarizeBy: none
		sourceColumn: NumCompaniesWorked

	column TrainingTimesLastYear
		dataType: int64
		lineageTag: 75ad7c9d-950b-4d3b-b96a-8a1aefef5f80
		summarizeBy: none
		sourceColumn: TrainingTimesLastYear

	column JobLevel
		dataType: int64
		lineageTag: 3aacbdac-222e-4153-ba05-fa9a639f0eda
		summarizeBy: none
		sourceColumn: JobLevel

	column JobInvolvement
		dataType: int64
		lineageTag: 3003d4d2-7f6e-4452-a788-4e737a921a65
		summarizeBy: none
		sourceColumn: JobInvolvement

	column JobSatisfaction
		dataType: int64
		lineageTag: 58b9df8e-b896-4aec-a8bf-b878a60f800f
		summarizeBy: none
		sourceColumn: JobSatisfaction

	column EnvironmentSatisfaction
		dataType: int64
		lineageTag: a9dee33c-47ea-407e-a17e-7e495d1d4c8c
		summarizeBy: none
		sourceColumn: EnvironmentSatisfaction

	column RelationshipSatisfaction
		dataType: int64
		lineageTag: 4bb977d5-ceb8-43d7-a148-e9a83bba748c
		summarizeBy: none
		sourceColumn: RelationshipSatisfaction

	column WorkLifeBalance
		dataType: int64
		lineageTag: 3a65dc01-2dac-4caf-b6b2-78781709d127
		summarizeBy: none
		sourceColumn: WorkLifeBalance

	column PerformanceRating
		dataType: int64
		lineageTag: dfd72e40-893b-4ee0-8365-eb39e2d73346
		summarizeBy: none
		sourceColumn: PerformanceRating

	column StockOptionLevel
		dataType: int64
		lineageTag: 473874a3-f001-4a58-bb02-2793d487af35
		summarizeBy: none
		sourceColumn: StockOptionLevel

	column ExperienceLevel
		dataType: string
		lineageTag: 85bbde03-b75c-4a0d-ae83-98e33a478603
		summarizeBy: none
		sourceColumn: ExperienceLevel

	column IncomeBand
		dataType: string
		lineageTag: b9c7eb35-b646-40a2-9a84-d65124ec4574
		summarizeBy: none
		sourceColumn: IncomeBand
		sortByColumn: IncomeBandSort

	column IncomeBandSort
		dataType: int64
		isHidden
		lineageTag: 23468a51-9c23-44e9-bac3-460a4b0ac13e
		summarizeBy: none
		sourceColumn: IncomeBandSort

	column TenureBand
		dataType: string
		lineageTag: 29eec4a4-6dd8-473e-9e5b-5ae13ec9f2e7
		summarizeBy: none
		sourceColumn: TenureBand
		sortByColumn: TenureBandSort

	column TenureBandSort
		dataType: int64
		isHidden
		lineageTag: 42487557-d950-4956-a477-5b61f23e0cee
		summarizeBy: none
		sourceColumn: TenureBandSort

	partition FactEmployee = m
		mode: import
		source =
				let
				    Source = Employees_Raw,
				    AddedAgeBand = Table.AddColumn(Source, "AgeBand", each if [Age] <= 25 then "18-25" else if [Age] <= 35 then "26-35" else if [Age] <= 45 then "36-45" else if [Age] <= 55 then "46-55" else "56-60", type text),
				    AddedExperience = Table.AddColumn(AddedAgeBand, "ExperienceLevel", each if [TotalWorkingYears] < 5 then "Junior (<5)" else if [TotalWorkingYears] <= 9 then "Mid (5-9)" else "Senior (10+)", type text),
				    AddedIncomeBand = Table.AddColumn(AddedExperience, "IncomeBand", each if [MonthlyIncome] < 2500 then "<2.5K" else if [MonthlyIncome] < 5000 then "2.5-5K" else if [MonthlyIncome] < 7500 then "5-7.5K" else if [MonthlyIncome] < 10000 then "7.5-10K" else if [MonthlyIncome] < 15000 then "10-15K" else "15-20K", type text),
				    AddedIncomeSort = Table.AddColumn(AddedIncomeBand, "IncomeBandSort", each if [MonthlyIncome] < 2500 then 1 else if [MonthlyIncome] < 5000 then 2 else if [MonthlyIncome] < 7500 then 3 else if [MonthlyIncome] < 10000 then 4 else if [MonthlyIncome] < 15000 then 5 else 6, Int64.Type),
				    AddedTenureBand = Table.AddColumn(AddedIncomeSort, "TenureBand", each if [YearsAtCompany] <= 1 then "0-1" else if [YearsAtCompany] <= 3 then "2-3" else if [YearsAtCompany] <= 5 then "4-5" else if [YearsAtCompany] <= 10 then "6-10" else if [YearsAtCompany] <= 20 then "11-20" else "21+", type text),
				    AddedTenureSort = Table.AddColumn(AddedTenureBand, "TenureBandSort", each if [YearsAtCompany] <= 1 then 1 else if [YearsAtCompany] <= 3 then 2 else if [YearsAtCompany] <= 5 then 3 else if [YearsAtCompany] <= 10 then 4 else if [YearsAtCompany] <= 20 then 5 else 6, Int64.Type),
				    JoinedDept = Table.NestedJoin(AddedTenureSort, {"Department"}, DimDepartment, {"Department"}, "jDept", JoinKind.LeftOuter),
				    ExpandedDept = Table.ExpandTableColumn(JoinedDept, "jDept", {"DepartmentKey"}),
				    JoinedRole = Table.NestedJoin(ExpandedDept, {"JobRole"}, DimJobRole, {"JobRole"}, "jRole", JoinKind.LeftOuter),
				    ExpandedRole = Table.ExpandTableColumn(JoinedRole, "jRole", {"JobRoleKey"}),
				    JoinedEdu = Table.NestedJoin(ExpandedRole, {"Education", "EducationField"}, DimEducation, {"Education", "EducationField"}, "jEdu", JoinKind.LeftOuter),
				    ExpandedEdu = Table.ExpandTableColumn(JoinedEdu, "jEdu", {"EducationKey"}),
				    JoinedDemo = Table.NestedJoin(ExpandedEdu, {"Gender", "MaritalStatus", "AgeBand"}, DimDemographics, {"Gender", "MaritalStatus", "AgeBand"}, "jDemo", JoinKind.LeftOuter),
				    ExpandedDemo = Table.ExpandTableColumn(JoinedDemo, "jDemo", {"DemographicsKey"}),
				    JoinedTravel = Table.NestedJoin(ExpandedDemo, {"BusinessTravel"}, DimTravel, {"BusinessTravel"}, "jTrav", JoinKind.LeftOuter),
				    ExpandedTravel = Table.ExpandTableColumn(JoinedTravel, "jTrav", {"TravelKey"}),
				    KeptColumns = Table.SelectColumns(ExpandedTravel, {"EmployeeNumber", "DepartmentKey", "JobRoleKey", "EducationKey", "DemographicsKey", "TravelKey", "Attrition", "OverTime", "Age", "MonthlyIncome", "MonthlyRate", "DailyRate", "HourlyRate", "PercentSalaryHike", "DistanceFromHome", "TotalWorkingYears", "YearsAtCompany", "YearsInCurrentRole", "YearsSinceLastPromotion", "YearsWithCurrManager", "NumCompaniesWorked", "TrainingTimesLastYear", "JobLevel", "JobInvolvement", "JobSatisfaction", "EnvironmentSatisfaction", "RelationshipSatisfaction", "WorkLifeBalance", "PerformanceRating", "StockOptionLevel", "ExperienceLevel", "IncomeBand", "IncomeBandSort", "TenureBand", "TenureBandSort"}),
				    Typed = Table.TransformColumnTypes(KeptColumns, {{"DepartmentKey", Int64.Type}, {"JobRoleKey", Int64.Type}, {"EducationKey", Int64.Type}, {"DemographicsKey", Int64.Type}, {"TravelKey", Int64.Type}})
				in
				    Typed

